/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coloresandrea;

import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Tarde
 */
public class PanelColoresPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelColoresPrincipal
     */
    public Colores getSelectedValues(){
        Colores c=new Colores(txtFondo.getBackground(),txtTexto.getBackground());
        
        return c;
    }
    public PanelColoresPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFondo = new javax.swing.JTextField();
        txtTexto = new javax.swing.JTextField();
        btnFondo = new javax.swing.JButton();
        btnTexto = new javax.swing.JButton();

        jLabel1.setText("Fondo");

        jLabel2.setText("Texto");

        txtFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFondoActionPerformed(evt);
            }
        });

        btnFondo.setText("...");
        btnFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFondoActionPerformed(evt);
            }
        });

        btnTexto.setText("...");
        btnTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(txtTexto))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFondo)
                    .addComponent(btnTexto))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFondo))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTexto))
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFondoActionPerformed
        // TODO add your handling code here:
        Color fondo=JColorChooser.showDialog(this,"Selecciona fondo", Color.WHITE);
        txtTexto.setBackground(fondo);
    }//GEN-LAST:event_txtFondoActionPerformed

    private void btnFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFondoActionPerformed
        // TODO add your handling code here:
        Color fondo=JColorChooser.showDialog(this,"Selecciona fondo", Color.WHITE);
        txtFondo.setBackground(fondo);
        
    }//GEN-LAST:event_btnFondoActionPerformed

    private void btnTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTextoActionPerformed
        // TODO add your handling code here:
        Color fondo=JColorChooser.showDialog(this,"Selecciona fondo", Color.WHITE);
        txtTexto.setBackground(fondo);
    }//GEN-LAST:event_btnTextoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFondo;
    private javax.swing.JButton btnTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFondo;
    private javax.swing.JTextField txtTexto;
    // End of variables declaration//GEN-END:variables
}
